### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arvl130** [arvl130/filipino-de-cuisine#10]
- [x] Ayusin ERD ng database Team
- [x] Update Prisma schema based on Database Team's ERD
- [x] Turuan database Team sa GitHub:
  - create ng branch
  - mag-commit
  - push
  - pull changes
- [x] Maglagay ng seed file sa Prisma
- [x] Ipakita yung Prisma studio sa Database group
- [x] I-edit yung package.json para may shortcuts for:
  - db:push
  - db:seed
  - db:studio
- [x] Online ordering flow
- [x] FAQs page
- [x] About Us page
- [x] Contact Us page
- [x] Sign In w/ Google
  - Collect Personal Information page (Name, Contact Number, Address)
- [x] Sign In w/ Facebook
- [x] Account Settings page
  - Edit Personal Information
  - Change Email & Password (only visible for users w/ Email as identity provider)
- [x] Paganahin Contact Us
- [x] Confirm before logging out, placing order
- [x] Save/Load basket from database
- [x] Should be able to select items to checkout in Basket.
- [x] Change validation behavior of Fill In Information form to onChange w/ input mask
- [x] Contact Form has has no horizontal padding
  - message field should use <textarea>
- [x] Reservation flow
- [x] Forgot Password page
- [x] Check if MenuItems are disabled
- [x] Save Additional notes to database.
- [x] Show order details even when paymentStatus is still pending
- [x] Remove vouchers
- [x] Receipts page
- [x] Order fees are not automatically refundable. Please contact our staff for more assistance.
  - in Cancel btn and checkout
- [x] Please fill out all required field
- [x] Integration w/ mobile and system
- [x] Use optimistic updates when updating basket item quantity
- [x] Reservation button should link to Sign In page if user is not logged in
- [x] Add Select All button for items in the Basket
- [x] Make the checkbox in Basket items bigger
- [x] Add GCash and Maya logo beside radio boxes
- [x] Show error modal when password is incorrect
- [x] Automatically apply discounts to Menu items
- [x] Paginate orders and reservations list
- [x] Responsive design
